#Travis Build setting.
language: java

install: skip

script: mvn package -DskipTests=true

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: target/speech-api-service-0.0.1-SNAPSHOT.jar
  skip_cleanup: true
  on:
    tags: false
  overwrite: true